### ISSUE TITLE
FLUORESCENCE SPECTRUM Layout for Repo

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/react-spectra-editor#133]
I’ve just checked some “.dx Fluorescence files” from the Repo and found a problem: While (j)dx is readable without Converter profiles but the problem is that “##DATA TYPE= FLUORESCENCE SPECTRUM” is not yet defined in ChemSpectra aka no such Layout exists.

@baolanlequang: Could you please create such a Layout for the Repo? As far as I understand the Technique, it is just a simple copy of the UVVIS Layout but with another Y-Label (Intensity instead of Absorbance). Attached you could find a dx-file to use without Converter (I tested it while changing the ##DATA TYPE to UVVIS and then it works on Test ELN).

Nicole needs it for some submitted data soon but doesn't give me an exact deadline.

Thanks and best wishes
David

**Comment by herrdivad** [comment]
@baolanlequang I've sent you the file via email because I'm unsure about making it public

**Comment by f-idiris** [comment]
This will be resolved by https://github.com/ComPlat/chem-spectra-app/pull/122 . 
JDX files of data type 'FLUORESCENCE SPECTRUM' will be recognized and set to the Emission spectrum layout by default.

**Comment by baolanlequang** [comment]
Done by https://github.com/ComPlat/chem-spectra-app/pull/122
