### ISSUE TITLE
GC Layout

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/react-spectra-editor#176]
Hi Team,

we'll please need a GC Layout for i.a. our "GC BID" device.
It contains two Chromatograms and optional a Temperature curve. Therefore the layout could be similar built like the SEC layout. 

- [ ] **In the short run:**

![ChemSpectra_GCLayout](https://github.com/ComPlat/react-spectra-editor/assets/113030128/68e23ae5-671b-44d6-a92c-a4170e93a6ba)
[Device File](https://github.com/ComPlat/react-spectra-editor/files/13438975/EF-R205.2__GC-BID_inc-5min-30_GC-3min-40-7min-180-2min_Calibrated_11142023_1210_002.gcd.txt)
[Bagit after Converter](https://github.com/ComPlat/react-spectra-editor/files/13438976/EF-R205.2__GC-BID_inc-5min-30_GC-3min-40-7min-180-2min_Calibrated_11142023_1210_002.gcd.zip)

- [ ] **I the long run:**

- Peak Picking
- Integration
- Background Subtraction
from Peaks

**Comment by baolanlequang** [comment]
Done by https://github.com/ComPlat/react-spectra-editor/pull/226
