### ISSUE TITLE
Enhance UI/UX for CV analyse

### ISSUE THREAD

**Issue by baolanlequang** [ComPlat/react-spectra-editor#85]
1. Add document link to Cyclic voltametry panel
2. Display all processed spectra from BagIt when users open chemspectra in ELN
3. Allow users can select dropdown files in chemspectra popup in difference way (maybe a button or users can move around the selection box, if possible)

**Comment by nicolejung** [comment]
please add a description

**Comment by baolanlequang** [comment]
Done at https://github.com/ComPlat/react-spectra-editor/pull/86
